### ISSUE TITLE
install and Configure tua-spa

### ISSUE THREAD

**Issue by boliveiratelco** [SAP-samples/cloud-commerce-sample-setup#25]
How install spartacus tua 3.x for SAP Commerce 2105 + telco and utilities 2111 using cloud-commerce-sample-setup?

I command execute  ng add @spartacus/tua-spa@3.1.0 
Change /js-storefront/spartacusstore/src/app/spartacus/spartacus.module.ts

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { ConfigModule } from '@spartacus/core';
import { translationChunksConfig, translations } from '@spartacus/assets';
import { TmaB2cStorefrontModule, tmaTranslations } from '@spartacus/tua-spa';
import { environment } from 'src/environments/environment';


@NgModule({
  declarations: [],
  imports: [
        TmaB2cStorefrontModule.withConfig({
      backend: {
        tmf: {
          baseUrl: environment.baseUrl,
          prefix: '/b2ctelcotmfwebservices',
          version: '/v2',
          endpoints: {
            getProduct: {
            baseUrl: environment.baseUrl,
            prefix: '/b2ctelcotmfwebservices',
            version: '/v3',
            endpoint: '/product/${id}'
            },
            getProductOffering: {
            baseUrl: environment.baseUrl,
            prefix: '/b2ctelcotmfwebservices',
            version: '/v3',
            endpoint: '/productOffering/${id}'
            }
          }
        },
        occ: {
          baseUrl: environment.baseUrl,
          prefix: '/occ/v2/',
        },
        tmf_appointment: {
          baseUrl: environment.baseUrl,
          prefix: '/tmf-api',
        },
        tmf_resource_pool_management: {
          baseUrl: environment.baseUrl,
          prefix: '/tmf-api',
        },
        premiseLookup: {
          baseUrl: environment.baseUrl,
          prefix: '/premise/v1/',
        }
      },
      context: {
        urlParameters: ['baseSite', 'language', 'currency'],
        baseSite: ['telcospa']
      },
      i18n: {
        resources: translations,
        chunks: translationChunksConfig,
        fallbackLang: 'en',
      },
      features: {
        level: '3.0'
      },
      journeyChecklist: {
        journeyChecklistSteps: ['APPOINTMENT', 'MSISDN', 'INSTALLATION_ADDRESS'],
        msisdn_reservation: {
          msisdn_qty: 1,
          msisdn_capacity_amount_demand: 1,
          msisdn_applied_capacity_amount: 5,
          applied_capacity_amount_for_msisdn_reservation: 1,
        },
        appointment: {
          requested_number_of_timeslots: 5,
          end_date_of_timeslots: 3,
        }
      },
      deliveryMode: {
        default_delivery_mode: 'not-applicable'
      }
    })
  ],
  exports: [TmaB2cStorefrontModule]
})
export class SpartacusModule { }
```

add package.json

    "chart.js": "^2.9.3",
    "ng2-charts": "^2.3.2",
    "ngx-spinner": "^9.0.1"

```
Compiling ng2-charts : es2015 as esm2015
/cloud-commerce-sample-setup-2105-spartacus/js-storefront/spartacusstore/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/targeted_entry_point_finder.js:40
                throw new Error("The target entry-point \"" + invalidTarget.entryPoint.name + "\" has missing dependencies:\n" +
                ^

Error: The target entry-point "@spartacus/tua-spa" has missing dependencies:
 - @spartacus/storefront/feature-toggles

    at TargetedEntryPointFinder.findEntryPoints (/cloud-commerce-sample-setup-2105-spartacus/js-storefront/spartacusstore/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/targeted_entry_point_finder.js:40:23)
    at /cloud-commerce-sample-setup-2105-spartacus/js-storefront/spartacusstore/node_modules/@angular/compiler-cli/ngcc/src/execution/analyze_entry_points.js:29:41
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (/cloud-commerce-sample-setup-2105-spartacus/js-storefront/spartacusstore/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:28:29)
    at /cloud-commerce-sample-setup-2105-spartacus/js-storefront/spartacusstore/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:57:59
    at SyncLocker.lock (/cloud-commerce-sample-setup-2105-spartacus/js-storefront/spartacusstore/node_modules/@angular/compiler-cli/ngcc/src/locking/sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (/cloud-commerce-sample-setup-2105-spartacus/js-storefront/spartacusstore/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:57:27)
    at Object.mainNgcc (/cloud-commerce-sample-setup-2105-spartacus/js-storefront/spartacusstore/node_modules/@angular/compiler-cli/ngcc/src/main.js:74:25)

```

**Comment by mpern** [comment]
Stale iasue
